language: python
services:
  - docker
python:
  - '3.6'
cache:
  directories:
  - node_modules
install:
  - npm install aglio
script:
  - 'docker build -t dojot/flowbroker .'
after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
